version: '3.4'

services:
  financialchat.webapp:
    image: ${DOCKER_REGISTRY-}financialchatwebapp
    build:
      context: .
      dockerfile: FinancialChat.WebApp/Dockerfile
  financialchat.bot.app:
    image: ${DOCKER_REGISTRY-}financialchatbotapp
    build:
      context: .
      dockerfile: FinancialChat.Bot.Api/Dockerfile
  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
